### ISSUE TITLE
It does not work on every server boot

### ISSUE THREAD

**Issue by andreaseriksson** [cpursley/walex#20]
I have an issue that it does not work on every server boot in my dev environment. When it works,
it works 100% and vice versa. My guess, some sort of race condition. The processes seem to be alive and seems to be the same in both scenarios.
 
dev.exs
```
config :tutorial, Tutorial.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "phx_tutorials_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :tutorial, WalEx,
  hostname: "localhost",
  username: "postgres",
  password: "postgres",
  port: "5432",
  database: "phx_tutorials_dev",
  publication: "events",
  subscriptions: [:companies],
  modules: [Tutorial.CompanyEvent],
  name: Tutorial
```

I run `Elixir 1.15.7 (compiled with Erlang/OTP 26)`

![bild](https://github.com/cpursley/walex/assets/897748/a462ec0d-e5cb-431e-b61a-710a331b7e06)

![bild](https://github.com/cpursley/walex/assets/897748/9d0528d1-1184-4013-92a3-4cc13dbc728c)

I run Postgres 15 (postgres.app)
and ran these and restarted the server:
```
ALTER SYSTEM SET wal_level = 'logical';
CREATE PUBLICATION events FOR ALL TABLES;
ALTER TABLE companies REPLICA IDENTITY FULL;
```

**Comment by andreaseriksson** [comment]
With 2.3.2 it works every time. Restared server about 15 times 😃

**Comment by andreaseriksson** [comment]
My guess its the module load order:
https://github.com/cpursley/walex/blob/master/lib/walex/events.ex#L37-L40

**Comment by cpursley** [comment]
@andreaseriksson I pushed up to master some changes that I think might fix this. I haven't put together a release yet so if you'd like to test, you can point at the repo.

https://github.com/cpursley/walex/blob/master/lib/walex/events.ex#L38

**Comment by andreaseriksson** [comment]
✅

**Comment by cpursley** [comment]
Actually, there's still some issues (around transactions). Working on getting those fixed.
