### ISSUE TITLE
DSL not working

### ISSUE THREAD

**Issue by DohanKim** [cpursley/walex#34]
problem: using DSL like README gives a compilation error (v 3.6.0)

reason: wrong macro definition 

the codes in the WalEx.Event is defining macro like below.

```
defmodule MacroModule do
  defmacro __using__(_) do
    quote do
      defmacro define_hello(do: block) do
        quote do
          def hello() do
            unquote(block).("hello world")
          end
        end
      end
    end
  end
end

defmodule Test do
  use MacroModule

  define_hello(do: fn x -> IO.puts(x) end)
end

Test.hello()
```

this code gives an error.

```
     error: undefined function define_hello/1 (there is no such import)
     
       define_hello(do: fn x -> IO.puts(x) end)
        ^
```

You intended something like the one below per README.

```
defmodule MacroModule do
  defmacro __using__(_) do
    quote do
      import MacroModule
    end
  end

  defmacro define_hello(do: block) do
    quote do
      def hello() do
        unquote(block).("hello world")
      end
    end
  end
end

defmodule Test do
  use MacroModule

  define_hello(do: fn x -> IO.puts(x) end)
end

Test.hello()
```

- p.s: Using macro like this is not encouraged
https://stackoverflow.com/questions/53065864/define-another-macro-inside-using

- it would be better to add test cases for the DSL usage.

- thank you for the effort to improve the library. I am gratefully using your library.

**Comment by cpursley** [comment]
Super, thank you @DohanKim !

What do you think of putting the Dsl logic into it's own module (dsl.ex or something like that)? This is something I've wanted to do for a while and keep event.ex just for the event struct & casting stuff.

**Comment by cpursley** [comment]
@DohanKim heads up that I just merged some additional changes to master which may break your PR. I think the main thing will be getting the events pid for tests will now work like this:

```
events_pid = find_worker_pid(destinations_supervisor_pid, DestinationsEventModules)
```

I moved Event under destinations and renamed the nodule to EventModules.

**Comment by DohanKim** [comment]
I agree with putting DSL logic into a separate module.
let me try to implement.

**Comment by DohanKim** [comment]
https://github.com/cpursley/walex/pull/36/commits/4a9a19a7318f650a4a0d66da562cc0c0b53de7be

- made separated dsl file 
- to use DSL, need to explicitly declare ``import WalEx.Event.Dsl`` such as
```
  use WalEx.Event, name: :test_app
  import WalEx.Event.Dsl
```

I think it's more clear to users than importing the Dsl macro implicitly in WalEx.Event.

- moved event-related files into the event folder
- fixed failing test you mentioned

**Comment by DohanKim** [comment]
it seems that you are not using the word and concept of "DSL" anymore in the README file, 
so making the macro imported implicitly look more natural. 
changed the PR accordingly
