### ISSUE TITLE
Set up Horde (for running on multiple nodes)

### ISSUE THREAD

**Issue by cpursley** [cpursley/walex#45]
https://github.com/cpursley/walex/issues/41

Similar to Nebulex

```elixir
defmodule MyApp.Cache do
  use Nebulex.Cache,
    otp_app: :my_app,
    adapter: Nebulex.Adapters.Horde,
    horde: [
      members: :auto,
      process_redistribution: :passive
      # any other Horde options ...
    ]
end
```

But perhaps just in regular config instead of a module.

**Comment by cpursley** [comment]
https://github.com/cpursley/walex/issues/41

**Comment by DaemonSnake** [comment]
heya
Any news on this ?

**Comment by cpursley** [comment]
I did some initial experiment but didn't get too far. Ran into a situation where multiple nodes were subscribes and I was still getting duplicate events. I'd love to see progress on this and open to ideas / PRs.

**Comment by cpursley** [comment]
Best handled in user's application.
