### ISSUE TITLE
Using Phoenix.PubSub

### ISSUE THREAD

**Issue by FabienHenon** [cpursley/walex#67]
Hi,

Thank you for your work here!

I'm just wondering why you do not provide a Phoenix.PubSub destination. It could be very useful, plus, it would be great to handle multiple nodes IMHO.
This way, every event is boradcasted to PubSub listeners. This makes it more convenient for realtime updates in liveview for instance.

Anyway, I'll probably need it, so I may create a PR ☺️

**Comment by cpursley** [comment]
You can publish pretty easily from on_event block (you can all any Elixir code).

I'm actually planning to depreciate destinations to keep the library small.

**Comment by FabienHenon** [comment]
That's good to know, thank you for your answer
