### ISSUE TITLE
Error: :erlang.binary_to_float("2222222")

### ISSUE THREAD

**Issue by phanmn** [cpursley/walex#8]
Thank you for awesome library!

Here is an error when I try to connect to my DB

<img width="680" alt="Screen Shot 2022-07-10 at 17 22 59" src="https://user-images.githubusercontent.com/3765536/178140923-d6ff5eb5-ab8d-4068-9f93-7dd90844b14e.png">

My work around is using (instead of to_float())

```
record |> Float.parse() |> elem(0)
```

**Comment by cpursley** [comment]
Thank you. Credit goes to Supabase realtime and cainophile ;)
